wandb_version: 1

epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.001
dropout:
  desc: null
  value: 0.7712450375643154
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704655032.792951
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.16
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
