wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704653313.601361
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.7.16
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
